=== k1LoW/tbls/spec/tbls.schema.json_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/k1LoW/tbls/schema/schema",
  "$ref": "#/$defs/Schema",
  "$defs": {
    "Column": {
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "nullable": {
          "type": "boolean"
        },
        "default": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "extra_def": {
          "type": "string"
        },
        "labels": {
          "$ref": "#/$defs/Labels"
        },
        "comment": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "type",
        "nullable"
      ]
    },
    "Constraint": {
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "def": {
          "type": "string"
        },
        "table": {
          "type": "string"
        },
        "referenced_table": {
          "type": "string"
        },
        "columns": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "referenced_columns": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "comment": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "type",
        "def",
        "table"
      ]
    },
    "Driver": {
      "properties": {
        "name": {
          "type": "string"
        },
        "database_version": {
          "type": "string"
        },
        "meta": {
          "$ref": "#/$defs/DriverMeta"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name"
      ]
    },
    "DriverMeta": {
      "properties": {
        "current_schema": {
          "type": "string"
        },
        "search_paths": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "dict": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Enum": {
      "properties": {
        "name": {
          "type": "string"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "values"
      ]
    },
    "Function": {
      "properties": {
        "name": {
          "type": "string"
        },
        "return_type": {
          "type": "string"
        },
        "arguments": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "return_type",
        "arguments",
        "type"
      ]
    },
    "Index": {
      "properties": {
        "name": {
          "type": "string"
        },
        "def": {
          "type": "string"
        },
        "table": {
          "type": "string"
        },
        "columns": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "comment": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "def",
        "table",
        "columns"
      ]
    },
    "Label": {
      "properties": {
        "name": {
          "type": "string"
        },
        "virtual": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name"
      ]
    },
    "Labels": {
      "items": {
        "$ref": "#/$defs/Label"
      },
      "type": "array"
    },
    "Relation": {
      "properties": {
        "table": {
          "type": "string"
        },
        "columns": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "cardinality": {
          "type": "string",
          "enum": [
            "zero_or_one",
            "exactly_one",
            "zero_or_more",
            "one_or_more",
            ""
          ]
        },
        "parent_table": {
          "type": "string"
        },
        "parent_columns": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "parent_cardinality": {
          "type": "string",
          "enum": [
            "zero_or_one",
            "exactly_one",
            "zero_or_more",
            "one_or_more",
            ""
          ]
        },
        "def": {
          "type": "string"
        },
        "virtual": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "table",
        "columns",
        "parent_table",
        "parent_columns",
        "def"
      ]
    },
    "Schema": {
      "properties": {
        "name": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "tables": {
          "items": {
            "$ref": "#/$defs/Table"
          },
          "type": "array"
        },
        "relations": {
          "items": {
            "$ref": "#/$defs/Relation"
          },
          "type": "array"
        },
        "functions": {
          "items": {
            "$ref": "#/$defs/Function"
          },
          "type": "array"
        },
        "enums": {
          "items": {
            "$ref": "#/$defs/Enum"
          },
          "type": "array"
        },
        "driver": {
          "$ref": "#/$defs/Driver"
        },
        "labels": {
          "$ref": "#/$defs/Labels"
        },
        "viewpoints": {
          "$ref": "#/$defs/Viewpoints"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "tables"
      ]
    },
    "Table": {
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        },
        "columns": {
          "items": {
            "$ref": "#/$defs/Column"
          },
          "type": "array"
        },
        "indexes": {
          "items": {
            "$ref": "#/$defs/Index"
          },
          "type": "array"
        },
        "constraints": {
          "items": {
            "$ref": "#/$defs/Constraint"
          },
          "type": "array"
        },
        "triggers": {
          "items": {
            "$ref": "#/$defs/Trigger"
          },
          "type": "array"
        },
        "def": {
          "type": "string"
        },
        "labels": {
          "$ref": "#/$defs/Labels"
        },
        "referenced_tables": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "type",
        "columns"
      ]
    },
    "Trigger": {
      "properties": {
        "name": {
          "type": "string"
        },
        "def": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "def"
      ]
    },
    "Viewpoint": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "labels": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "tables": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "distance": {
          "type": "integer"
        },
        "groups": {
          "items": {
            "$ref": "#/$defs/ViewpointGroup"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "desc"
      ]
    },
    "ViewpointGroup": {
      "properties": {
        "name": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "labels": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "tables": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "color": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "desc"
      ]
    },
    "Viewpoints": {
      "items": {
        "$ref": "#/$defs/Viewpoint"
      },
      "type": "array"
    }
  }
}

=== k1LoW/tbls/sample/adjust/schema.json
{
  "name": "testdb",
  "desc": "Sample PostgreSQL database document.",
  "tables": [
    {
      "name": "public.users",
      "type": "BASE TABLE",
      "comment": "Users table",
      "columns": [
        {
          "name": "id",
          "type": "integer",
          "nullable": false,
          "default": "nextval('users_id_seq'::regclass)"
        },
        {
          "name": "username",
          "type": "varchar(50)",
          "nullable": false
        },
        {
          "name": "password",
          "type": "varchar(50)",
          "nullable": false
        },
        {
          "name": "email",
          "type": "varchar(355)",
          "nullable": false,
          "comment": "ex. user@example.com"
        },
        {
          "name": "created",
          "type": "timestamp without time zone",
          "nullable": false
        },
        {
          "name": "updated",
          "type": "timestamp without time zone",
          "nullable": true
        }
      ],
      "indexes": [
        {
          "name": "users_pkey",
          "def": "CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id)",
          "table": "public.users",
          "columns": [
            "id"
          ]
        },
        {
          "name": "users_username_key",
          "def": "CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username)",
          "table": "public.users",
          "columns": [
            "username"
          ]
        },
        {
          "name": "users_email_key",
          "def": "CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email)",
          "table": "public.users",
          "columns": [
            "email"
          ]
        }
      ],
      "constraints": [
        {
          "name": "users_username_check",
          "type": "CHECK",
          "def": "CHECK ((char_length((username)::text) \u003e 4))",
          "table": "public.users",
          "referenced_table": "",
          "columns": [
            "username"
          ]
        },
        {
          "name": "users_pkey",
          "type": "PRIMARY KEY",
          "def": "PRIMARY KEY (id)",
          "table": "public.users",
          "referenced_table": "",
          "columns": [
            "id"
          ]
        },
        {
          "name": "users_username_key",
          "type": "UNIQUE",
          "def": "UNIQUE (username)",
          "table": "public.users",
          "referenced_table": "",
          "columns": [
            "username"
          ]
        },
        {
          "name": "users_email_key",
          "type": "UNIQUE",
          "def": "UNIQUE (email)",
          "table": "public.users",
          "referenced_table": "",
          "columns": [
            "email"
          ]
        }
      ],
      "triggers": [
        {
          "name": "update_users_updated",
          "def": "CREATE TRIGGER update_users_updated AFTER INSERT OR UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_updated()",
          "comment": "Update updated when users insert or update"
        }
      ]
    },
    {
      "name": "public.user_options",
      "type": "BASE TABLE",
      "comment": "User options table",
      "columns": [
        {
          "name": "user_id",
          "type": "integer",
          "nullable": false
        },
        {
          "name": "show_email",
          "type": "boolean",
          "nullable": false,
          "default": "false"
        },
        {
          "name": "created",
          "type": "timestamp without time zone",
          "nullable": false
        },
        {
          "name": "updated",
          "type": "timestamp without time zone",
          "nullable": true
        }
      ],
      "indexes": [
        {
          "name": "user_options_pkey",
          "def": "CREATE UNIQUE INDEX user_options_pkey ON public.user_options USING btree (user_id)",
          "table": "public.user_options",
          "columns": [
            "user_id"
          ],
          "comment": "PRIMARY KEY"
        }
      ],
      "constraints": [
        {
          "name": "user_options_user_id_fk",
          "type": "FOREIGN KEY",
          "def": "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE",
          "table": "public.user_options",
          "referenced_table": "public.users",
          "columns": [
            "user_id"
          ],
          "referenced_columns": [
            "id"
          ],
          "comment": "FK"
        },
        {
          "name": "user_options_pkey",
          "type": "PRIMARY KEY",
          "def": "PRIMARY KEY (user_id)",
          "table": "public.user_options",
          "referenced_table": "",
          "columns": [
            "user_id"
          ]
        }
      ]
    },
    {
      "name": "public.posts",
      "type": "BASE TABLE",
      "comment": "Posts table",
      "columns": [
        {
          "name": "id",
          "type": "bigint",
          "nullable": false,
          "default": "nextval('posts_id_seq'::regclass)"
        },
        {
          "name": "user_id",
          "type": "integer",
          "nullable": false
        },
        {
          "name": "title",
          "type": "varchar(255)",
          "nullable": false,
          "default": "'Untitled'::character varying"
        },
        {
          "name": "body",
          "type": "text",
          "nullable": false,
          "comment": "post body"
        },
        {
          "name": "post_type",
          "type": "post_types",
          "nullable": false,
          "comment": "public/private/draft"
        },
        {
          "name": "labels",
          "type": "varchar(50)[]",
          "nullable": true
        },
        {
          "name": "created",
          "type": "timestamp without time zone",
          "nullable": false
        },
        {
          "name": "updated",
          "type": "timestamp without time zone",
          "nullable": true
        }
      ],
      "indexes": [
        {
          "name": "posts_id_pk",
          "def": "CREATE UNIQUE INDEX posts_id_pk ON public.posts USING btree (id)",
          "table": "public.posts",
          "columns": [
            "id"
          ]
        },
        {
          "name": "posts_user_id_title_key",
          "def": "CREATE UNIQUE INDEX posts_user_id_title_key ON public.posts USING btree (user_id, title)",
          "table": "public.posts",
          "columns": [
            "user_id",
            "title"
          ]
        },
        {
          "name": "posts_user_id_idx",
          "def": "CREATE INDEX posts_user_id_idx ON public.posts USING btree (user_id)",
          "table": "public.posts",
          "columns": [
            "user_id"
          ],
          "comment": "posts.user_id index"
        }
      ],
      "constraints": [
        {
          "name": "update_posts_updated",
          "type": "TRIGGER",
          "def": "CREATE CONSTRAINT TRIGGER update_posts_updated AFTER INSERT OR UPDATE ON public.posts NOT DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION update_updated()",
          "table": "public.posts",
          "referenced_table": ""
        },
        {
          "name": "posts_user_id_fk",
          "type": "FOREIGN KEY",
          "def": "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL (user_id)",
          "table": "public.posts",
          "referenced_table": "public.users",
          "columns": [
            "user_id"
          ],
          "referenced_columns": [
            "id"
          ],
          "comment": "posts -\u003e users"
        },
        {
          "name": "posts_id_pk",
          "type": "PRIMARY KEY",
          "def": "PRIMARY KEY (id)",
          "table": "public.posts",
          "referenced_table": "",
          "columns": [
            "id"
          ]
        },
        {
          "name": "posts_user_id_title_key",
          "type": "UNIQUE",
          "def": "UNIQUE (user_id, title)",
          "table": "public.posts",
          "referenced_table": "",
          "columns": [
            "user_id",
            "title"
          ]
        }
      ],
      "triggers": [
        {
          "name": "update_posts_updated",
          "def": "CREATE CONSTRAINT TRIGGER update_posts_updated AFTER INSERT OR UPDATE ON public.posts NOT DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION update_updated()",
          "comment": "Update updated when posts update"
        }
      ]
    },
    {
      "name": "public.comments",
      "type": "BASE TABLE",
      "comment": "Comments\nMulti-line\r\ntable\rcomment",
      "columns": [
        {
          "name": "id",
          "type": "bigint",
          "nullable": false,
          "default": "nextval('comments_id_seq'::regclass)"
        },
        {
          "name": "post_id",
          "type": "bigint",
          "nullable": false
        },
        {
          "name": "user_id",
          "type": "integer",
          "nullable": false
        },
        {
          "name": "comment",
          "type": "text",
          "nullable": false,
          "comment": "Comment\nMulti-line\r\ncolumn\rcomment"
        },
        {
          "name": "post_id_desc",
          "type": "bigint",
          "nullable": true,
          "extra_def": "GENERATED ALWAYS AS (post_id * '-1'::integer) STORED"
        },
        {
          "name": "created",
          "type": "timestamp without time zone",
          "nullable": false
        },
        {
          "name": "updated",
          "type": "timestamp without time zone",
          "nullable": true
        }
      ],
      "indexes": [
        {
          "name": "comments_id_pk",
          "def": "CREATE UNIQUE INDEX comments_id_pk ON public.comments USING btree (id)",
          "table": "public.comments",
          "columns": [
            "id"
          ]
        },
        {
          "name": "comments_post_id_user_id_key",
